.gitignore

폴더 구조 정리
- controllers, lib, middlewares 추가
- .gitignore에 swagger-output 추가
2022.04.25 복지리
commit by jiwon

feat(basic): folder structure

---

controllers/mainController.js
controllers/markController.js
controllers/tipController.js
controllers/userController.js
middlewares/users/auth-middleware.js
routes/index.js
routes/main.js
routes/mark.js
routes/tip.js
routes/user.js

폴더 구조 정리
- spec.js 모든 파일 추가(CI/CD & TDD)
- prettier 적용
2022.04.25 복지리
commit by jiwon

feat(basic): folder structure with TDD

---

.prettierignore
app.js
appspec.yml
ecosystem.json
routes/main.js
scripts/after.install.sh

지속적 배포
- 스크립트 없이 테스트
2022.04.25 복지리

feat(CD): Continuous Deployment

---

models/index.js

DB 모델 추가
- sequelize-auto를 사용하기 위한 index.js 추가
2022.04.25 복지리

feat(db): db models

---

app.spec.js
controllers/mainController.spec.js
controllers/markController.spec.js
controllers/tipController.spec.js
controllers/userController.spec.js
middlewares/users/auth-middleware.spec.js
routes/index.spec.js
routes/main.spec.js
routes/mark.spec.js
routes/tip.spec.js
routes/user.spec.js

유닛 테스트 코드 시험 작성
2022.04.25 복지리
commit by jiwon

feat(unitTset): create unit test code for TDD

---

appspec.yml
scripts/after.install.sh

ec2 내부 바뀐 폴더구조에 맞게 코드 변경
2022.04.25 복지리

feat(CD): consturcture for CD

---

appspec.yml
scripts/application.start.sh
scripts/application.stop.sh

pm2 restart를 하지않고 stop 후 다시 start 하도록 수정
2022.04.26 복지리

feat(CD): setting for CD

---

openAPI/index.js
openAPI/output.txt
openAPI/output2.txt
package-lock.json
package.json

openAPI에서 불러온 데이터 txt 파일에 저장
2022.04.27 복지리

feat(DC): Data Cleansing

---

app.js
controllers/auth.controller.js
controllers/user.controller.js
openAPI/index.js
package-lock.json
package.json
routes/auth.js
routes/mark.js
routes/user.js
schemas/index.js
services/user.service.js

카카오 로그인 회원가입 기능 추가
2022.04.28 복지리

feat(auth): sign in sign up

---

app.js
controllers/mark.controller.js
routes/mark.js
services/mark.service.js

feat(mark):test mongo

---

app.js

app.user(cors()) 추가
2022.04.28 복지리

feat(auth): cors

---

controllers/user.controller.js

redirect url 변경
2022.04.28 복지리

feat(auth): redirect

---

app.js

cors 옵션에 https 도메인으로 변경
2022.04.28 복지리

feat(ssl): https

---

app.js

cors origin에 카카오 추가
2022.04.29 복지리

feat(cors): cors option revise

---

controllers/mark.controller.js
controllers/specs/mark.spec.js
routes/specs/mark.spec.js
services/mark.service.js

-북마크 코드 수정
-북마크 유닛테스트 수정
-북마크 통합테스트 1차 완성
2022-04-30 복지리

fix(mark):mark, unit test, Int test

---

server.js

누가 https 주석처리했어!!
2022.04.30 복지리

feat(server): https

---

.gitignore
schemas/user.js

feat(schema): user schema revise 

---

middlewares/auth/auth.middleware.js

auth.middleware 수정
- try catch로 error 핸들링
2022.05.01 복지리

feat(authmiddleware): auth.middleware refactoring

---

controllers/mark.controller.js
middlewares/redis.middleware.js
routes/mark.js
schemas/redis.js
services/mark.service.js

- schemas redis 추가
- redis middleware 추가
2022.05.01 복지리

feat(mark): add redis

---

controllers/mark.controller.js
package-lock.json
package.json
routes/mark.js
routes/tip.js
services/mark.service.js

- 북마크 top5 기능 추가
- redis 코드 수정
- nodemon 버전 업
2022.05.01 복지리

feat(mark): add top5 Mark

---

controllers/mark.controller.js
middlewares/redis.middleware.js
routes/mark.js
schemas/user.js
services/mark.service.js

-북마크 좋아요 기능 추가
-Model 좋아요 상위 북마크 추가
2022.05.02 복세편살

feat(mark) add mark like

---

controllers/main.controller.js
services/main.service.js

main GET API 개발
- 메인 페이지에서 유저 정보를 토대로 개인별 정책을 추천해주는 api
2022.05.02 복세편살

feat(mainAPI): develop main GET API

---

controllers/mark.controller.js
controllers/tip.controller.js
services/tip.service.js
tipLog.txt

-버그 제보 기능 추가
-버그 제보 데이터 txt 파일에 저장
2022.05.02 복세편살

feat(tip):add tip

---

controllers/auth.controller.js
controllers/specs/user.spec.js
middlewares/auth/auth.middleware.spec.js
openAPI/indexdex.js
openAPI/indexdexdex.js

새 openAPI추가 데이터 txt파일에 저장
2022.05.03 복지리

feat(openAPI): openAPI 추가

---

.github/workflows/node.js.yml
.prettierignore

github secret에 추가된 환경변수가 workflows에서 적용 되도록 하는 코드 추가
2022.05.03 복세편살

feat(workflows): workflows github secret 환경변수 추가

---

controllers/auth.controller.js

feat(auth): kakao login

---

services/user.service.js

findOne 으로 찾으면 데이터가 삭제된 다음에 찾아도 에러를 뱉지 않은 find로 수정함

feat(user): check user

---

controllers/main.controller.js
controllers/specs/main.spec.js

fix(mainAPI): develop main GET API

---

middlewares/auth/auth.middleware.js

feat(middlewares): middlewares res.locals 수정

---

controllers/main.controller.js
controllers/specs/main.spec.js
services/main.service.js

- query로 필수입력값 입력하지 않으면 에러 추가
- DB 조회 실패 에러 추가
- DB/Data 한번만 조회하게끔 수정
- 이후 코드 리펙토링이 수월하게끔 일관된 코드로 수정
unit test code 추가
swagger 추가

fix(mainAPI): getMain & add swagger, unit test

---

controllers/main.controller.js
controllers/specs/main.spec.js
routes/main.js

main GET API url 수정
query -> params

fix(mainAPI): modify getMain API url

---

controllers/detail.controller.js
routes/detail.js
routes/index.js
services/detail.service.js

feat(detail): 상세정보조회 api  추가

---

.gitignore
tipLog.txt

feat(github): log.txt

---

services/tip.service.js

fix(tip):txt file name 변경

---

services/main.service.js

fix(mainAPI): checkedData includes undefined data

---

controllers/news.controller.js

fix(news): news 내용 수정

---

controllers/main.controller.js

res에 checkedData 이외의 카테고리
work, houseLife, health, eduCare, safetyRight, etc 추가

fix(mainAPI): create category of checkedData

---

controllers/main.controller.js
services/main.service.js

checkedData에 분류 기준이 모두 undefined인 data 모두 필터링
2022.05.05 복세편살

fix(mainAPI): cleansing checkedData

---

controllers/news.controller.js
schemas/news.js

- news Collection 생성
- 뉴스 코드 수정
2022.어린이날

fix(news): news 기능 수정

---

controllers/news.controller.js

feat(news): news 기능 수정

---

controllers/user.controller.js
schemas/user.js
services/user.service.js

feat(user): user 수정

---

controllers/mark.controller.js
controllers/news.controller.js

fix(mark):삭제기능 수정

---

controllers/mark.controller.js
schemas/user.js
services/mark.service.js

fix(mark):북마크 삭제 수정

---

controllers/mark.controller.js
openAPI/gender.js
services/mark.service.js

fix(mark):북마크 json 수정

---

controllers/mark.controller.js
controllers/news.controller.js
openAPI/scholarship.js

- 학력, 성별 데이터 클렌징
- 뉴스 조회 개수 변경

feat(news,data) 데이터클렌징, 뉴스개수 수정

---

openAPI/marriage.js
services/news.service.js

fix(news):node-schedule tz설정

---

services/news.service.js

feat(news):node-schedule 자동 업데이트

---

openAPI/marriage.js
routes/news.js
services/news.service.js

fix(news):레디스 제거 테스트

---

controllers/news.controller.js
services/news.service.js

fix(news):try catch 추가

---

routes/news.js
services/news.service.js

feat(news):뉴스 오류 수정

---

controllers/tip.controller.js
routes/tip.js
services/news.service.js
services/tip.service.js

- authmiddleware 추가
- 오류처리
- 버그제보한 날짜 추가

fix(tips):버그제보 코드 보완

---

controllers/auth.controller.js
controllers/specs/user.spec.js
controllers/user.controller.js
routes/user.js
services/user.service.js

userservice findOne console.log
userservice 테스트코드수정

feat(user): userservice findOne console.log

---

controllers/auth.controller.js
services/user.service.js

if(!user)로 하면 안되고 if(user === null)로 하니까 됨

feat(user): userservice findOne

---

routes/main.js

fix(swagger): create swagger

---

scripts/after.install.sh

feat(CD): hook에  swagger추가

---

services/main.service.js

fix main api
- forEach가 데이터의 순서를 무작위적으로 바꿈
- > for문으로 전부 수정

fix(mainAPI): modify forEach to for

---

controllers/main.controller.js
services/main.service.js

fix main api
- 중복 제거 함수 추가
- forEach가 데이터의 순서를 무작위적으로 바꿈
-> for문으로 수정

fix(mainAPI): add eliminate deduplication fn

---

controllers/auth.controller.js
services/user.service.js

feat(user): user findOne -> find

---

controllers/auth.controller.js
controllers/user.controller.js
middlewares/auth/auth.middleware.js
services/user.service.js

throw new Error() 삭제하고 null을 리턴하도록 변경

feat(user): user find -> findOne

---

controllers/mark.controller.js
controllers/search.controller.js
package-lock.json
package.json
routes/index.js
routes/search.js
schemas/index.js
schemas/news.js
services/news.service.js
services/search.service.js

- npm axios, cheerio 추가
- 뉴스 크롤링으로 방식 변경
- 검색기능 1차 구현(미완성)

feat(news,search):뉴스 크롤링으로 변경, search 미완성

---

services/news.service.js

fix(news): news 데이터 정렬

---

controllers/main.controller.js
services/main.service.js

- DB를 거치지 않는 service 파일의 함수를 controller로 병합
- trycatch 수정
- console.error(error) 수정

fix(mainAPI): modify getMain

---

openAPI/index.youth.js
schemas/data.js

나이 기준 더 자세하게 수정
데이터 스키마에 process 추가

feat(openAPI): 나이 기준 수정

---

openAPI/gender.js
openAPI/marriage.js
openAPI/scholarship.js
schemas/data.js

feat(marriage):결혼 데이터 분류

---

controllers/detail.controller.js
services/detail.service.js

feat(detail): detail res 변경

---

app.js
openAPI/crawling.js
openAPI/index.youth.js

feat(openAPI): 자동화

---

controllers/main.controller.js
services/main.service.js
services/search.service.js

getMain 코드 리펙토링
- service 함수들 이름 간결하게 수정(checkUser, checkData)
- checkUser에 만 나이 계산식 추가 & lifeCycle 계산식 추가
>주의 search.service 코드가 리펙토링에 영향을 받음
getMain 조건 검사
- age/lifeCycle
- disability/obstacle
- gender
- region

feat(getMain): 조건 검사 로직 추가

---

controllers/main.controller.js

getMain API region 조건 검사 오류
- region에 상관 없이 받을 수 있는 정책 나타나게 수정

fix(getMain): region 조건 검사 오류 수정

---

controllers/main.controller.js

fix(getMain): 중복 제거 함수 오류 수정

---

controllers/user.controller.js
schemas/user.js
services/user.service.js

feat(user): family 추가

---

appspec.yml
scripts/application.start.sh
scripts/application.stop.sh

feat(CD): pm2 kill pm2 start 설정

---

appspec.yml

feat(CD):hook 제거

---

ecosystem.json

feat(pm2): pm2 ecosystem 설정

---

logging.js

fix(log): 로그파일 경로 수정

---

app.js
dataUpdating/index.js
ecosystem.json
openAPI/index.youth.js

feat(openAPI):자동화 적용

---

dataUpdating/index.js

feat(openAPI): openAPI log 위치 변경

---

dataUpdating/index.js

feat(openAPI): openAPI log 위치 환경변수 설정

---

scripts/after.install.sh

feat(CD): hook 변경

---

controllers/main.controller.js

getMain 조건 검사 코드 분리
- exports logic fn

refactor(getMain): logic 조건 검사 코드 분리

---

controllers/main.controller.js
services/main.service.js

fix(getMain): logic console.error 추가

---

controllers/main.controller.js

salary 조건 검사 버그 수정
- isUser.salary === undifined -> !isUser.salary

fix(getMain): salary 조건 검사 버그 수정

---

controllers/main.controller.js
controllers/mark.controller.js
controllers/search.controller.js
routes/search.js
services/search.service.js

feat(search): 프론트 통신 테스트

---

services/search.service.js

feat(검색): 검색기능 1차 완료!

---

controllers/user.controller.js
routes/user.js
services/detail.service.js
services/user.service.js
validator/user.validator.js

feat(user): validator 추가

---

controllers/mark.controller.js
controllers/news.controller.js
routes/mark.js
routes/news.js

- res.locals로 변경
- 사용자 인증 미들웨어 추가
- 로그 에러처리

feat(mark,news): authmiddleware 추가

---

controllers/mark.controller.js

fix(mark): 유저 검사 수정

---

controllers/mail.controller.js
dataUpdating/index.js
openAPI/index.youth.js
package-lock.json
package.json
routes/index.js
routes/mail.js
services/mail.service.js
swagger.js

feat(mail): 메일보내기 추가, fix(openAPI): 받을 때마다 정보가 달라지던 문제 수정

---

controllers/main.controller.js

fix(getMain): Error logging

---

controllers/detail.controller.js
controllers/mail.controller.js
controllers/user.controller.js

feat(user): stack error 추가

---

services/mail.service.js

feat(mail): require 삭제

---

controllers/mark.controller.js

fix(mark):프론트 상태저장 응답값 추가

---

controllers/mark.controller.js
services/mark.service.js

fix(mark): 프론트 상태 응답변경

---

validator/user.validator.js

feat(user): validation 수정

---

controllers/user.controller.js

feat(user): get 할때 시·군을 선택해 주세요 추가

---

controllers/main.controller.js
services/main.service.js

getMain service data에서 북마크 여부 체크

feat(getMain):북마크 여부 체크

---

controllers/user.controller.js

feat(user): user

---

controllers/user.controller.js

feat(dev): to main from dev

---

app.js
controllers/mark.controller.js
controllers/search.controller.js
dataCleansing/cleansing.js
dataCleansing/data.js
services/mark.service.js

feat(search): 검색기능 수정

---

services/main.service.js

getMain service data에서 북마크 여부 체크 오류 수정
2022.05.14 복세편살

fix(getMain):북마크 여부 체크 오류 수정

---

controllers/detail.controller.js
controllers/mark.controller.js
controllers/search.controller.js
controllers/user.controller.js

create swagger
- user
- search
modify swagger
- mark
- detail
2022.05.14 복세편살

feat(swagger): create user, search swagger

---

controllers/mark.controller.js
services/mark.service.js

- 중복데이터 북마크불가
- DB에 없는 데이터 북마크 불가
2022.05.14 복세편살

fix(북마크):코드 수정

---

controllers/main.controller.js

getMain logic에서 유저의 기준이 없을 때 상관없음만 보여주는 방식으로 수정
2022.05.16 복세편살

fix(getMain): getMain logic 오류 수정

---

dataUpdating/index.js
openAPI/index.js
validator/validator.array.js

feat(openAPI): axios로 변경

---

controllers/main.controller.js

getMain logic 코드 리펙토링
2022.05.16 복세편살

refactor(getMain): getMain logic 코드 리펙토링

---

app.js
dataCleansing/data.js
dataUpdating/index.js
openAPI/index.age.js
openAPI/index.js

dev 인스턴스와 main 인스턴스에서 중복작업이 발생하지 않도록 환경변수 추가

feat(openAPI): 자동화 환경변수 추가

---

openAPI/index.salary.js

중위소득기준 추가
카테고리에 저소득은 있는데 중위소득이 없는 경우 중위소득 기준을 50으로 설정
2022.05.16 복세편살

feat(openAPI): salary 추가

---

controllers/main.controller.js

getMain age logic 코드 수정
2022.05.17 복세편살

fix(getMain): getMain age logic 수정

---

services/main.service.js

getMain에서 dismatchData를 추천하지 않는 기능 추가
2022.05.17 복세편살

feat(getMain): getMain dismatchData 기능 추가

---

controllers/mark.controller.js
controllers/specs/mark.spec.js
controllers/specs/tip.spec.js
controllers/tip.controller.js
dataCleansing/cleansing.js
dataCleansing/data.js
routes/mark.js
schemas/data.js
services/mark.service.js
services/tip.service.js

- 북마크 테스트코드 수정
- tip 테스트코드 작성
- 북마크 상태값 수정
- 업종 데이터 클랜징
2022.05.17 복세편살

feat(testcode,mark,datacleansing)

---

controllers/main.controller.js
services/main.service.js

getMain 수정 
- 나이 로직 수정
- dismatchData 추가

feat(getMain): getMain salary 조건 검사 정교화

---

openAPI/index.age.js
openAPI/index.js
openAPI/index.salary.js
schemas/data.js

age 기준 추가
schemas/data에 criteria 추가
2022.05.17 복세편살

feat(openAPI): age 추가

---

dataUpdating/youth.age.js
openAPI/index.age.js
openAPI/index.js
openAPI/index.salary.js

feat(openAPI): salary 추가중

---

controllers/mark.controller.js
controllers/specs/mark.spec.js
routes/mark.js

feat(mark): bookmarkState

---

controllers/detail.controller.js
controllers/user.controller.js
openAPI/index.salary.js
schemas/user.js
services/user.service.js
validator/user.validator.js
validator/validator.array.js

feat(user): user 정보 workType 추가

---

validator/user.validator.js

feat(user): 오타수정

---

controllers/main.controller.js
controllers/specs/main.spec.js

getMain workType 조건 검사 logic 추가

feat(getMain): getMain workType logic 추가

---

controllers/specs/user.spec.js
dataUpdating/index.js
dataUpdating/youth.age.js

제한없음으로 나와있어도 청년정책이니까 임의로 20세부터 39세 까지로 설정

feat(openAPI): 제한없음 조건 수정

---

controllers/search.controller.js
controllers/specs/mark.spec.js
controllers/specs/news.spec.js
controllers/specs/tip.spec.js
controllers/tip.controller.js
routes/specs/mark.spec.js
services/mark.service.js

- news test 추가
- tip 테스트 보완
- mark test 보완

feat(test):테스트코드 보완

---

controllers/mail.controller.js
controllers/specs/detail.spec.js
controllers/user.controller.js
routes/mail.js
routes/specs/user.spec.js
routes/user.js
schemas/user.js
services/mail.service.js
services/user.service.js

사이트 자체 회원가입전에 메일로 본인인증 추가(카카오로그인이랑 연동할 때 필요)
사이트 자체 회원가입 로그인 추가 카카오랑 아직 연동 안됨

feat(user): 회원가입 로그인 인증메일발송 인증코드 검증 추가

---

controllers/search.controller.js

feat(search): 특수문자 제외

---

package-lock.json
package.json
routes/specs/user.spec.js
schemas/index.js

feat(user): 통합테스트 추가

---

app.js
routes/specs/mark.spec.js
routes/specs/user.spec.js

feat(app): sameSite규칙 삭제

---

controllers/main.controller.js
controllers/specs/main.spec.js

getMain 배포 버전 정리
- console.log 주석
- test 코드 정리

fix(getMain): getMain 배포 버전 정리

---

controllers/mark.controller.js
controllers/search.controller.js
controllers/tip.controller.js
routes/specs/mark.spec.js
services/mark.service.js
services/tip.service.js

feat(test):console 제거

---

package.json

feat(app): cross-env 추가

---

routes/specs/mark.spec.js

feat(spec): 임시 통과 코드 추가

---

.github/workflows/node.js.yml

feat(CI): secrets 추가

---

.github/workflows/node.js.yml
controllers/specs/mark.spec.js
package-lock.json
package.json

feat(spec): dotenv 추가

---

services/main.service.js

fix(getMain): console 제거

---

.github/workflows/node.js.yml

feat(CI): secrets추가

---

.github/workflows/node.js.yml
app.js

feat(CI): 환경변수 추가

---

routes/specs/user.spec.js

feat(user): disconnect 추가

---

package.json
routes/specs/user.spec.js

feat(user): connect test

---

controllers/specs/tip.spec.js
controllers/tip.controller.js
services/tip.service.js

feat(test):테스트코드 주석 처리

---

controllers/mark.controller.js
controllers/specs/mark.spec.js
controllers/specs/tip.spec.js
controllers/tip.controller.js
routes/mark.js
services/mark.service.js
services/tip.service.js

feat(mark):북마크 delete api 추가

---

services/mark.service.js

fix(mark): put 수정

---

controllers/mark.controller.js
controllers/specs/mark.spec.js
controllers/specs/tip.spec.js
controllers/tip.controller.js
package.json
routes/mark.js
routes/specs/user.spec.js
services/mark.service.js
services/tip.service.js
test/user/patch.json

feat(dev) to main from dev

---

controllers/mark.controller.js
controllers/search.controller.js
controllers/specs/mark.spec.js
controllers/specs/tip.spec.js
controllers/tip.controller.js

feat(search):공백 추가

---

routes/specs/auth.spec.js
routes/specs/detail.spec.js
routes/specs/index.spec.js
routes/specs/user.spec.js
test/data/sample.json

feat(detail): 통합테스트 추가

---

validator/user.validator.js

feat(user): validate 추가

---

controllers/main.controller.js

salary 0일 때 저소득 정책 줌
salary null/undefined일때 추천 x

fix(getMain): salary logic 수정

---

app.spec.js
routes/specs/detail.spec.js

feat(app): 통합테스트 추가

---

controllers/search.controller.js

fix(search):통합검색으로 변경

---

app.js
controllers/news.controller.js
middlewares/redis.middleware.js
routes/news.js
schemas/news.js
services/news.service.js

feat(news):지역 맞춤 뉴스

---

app.js
controllers/news.controller.js
controllers/search.controller.js
middlewares/redis.middleware.js
routes/news.js
schemas/news.js
services/news.service.js

feat(dev):go main!

---

policies/services/detail.service.js

detail 지원 대상, 서비스 내용 줄바꿈 추가
2022.05.21 복세편살

fix(detail): detail 줄바꿈

---

policies/services/detail.service.js

detail 지원 대상, 서비스 내용, 요약 줄바꿈 방식 여러가지로 추가
2022.05.22 복세편살

fix(detail): detail 줄바꿈 retry

---

API/news/services/news.service.js

서버에 뉴스 콘솔로그 계속 찍혀서 주석처리했습니다.
@rlasuddn 영우님 확인 해주시면 merge 할게요.
2022.05.22 복세편살

fix(news):console.log 제거

---

API/mail/controllers/mail.controller.js
API/mail/index.js
API/mail/index.spec.js
API/mail/validator/cert.validator.js
API/mail/validator/mail.validator.js
API/policies/controllers/detail.controller.js
API/policies/index.js
API/policies/index.spec.js
API/users/validators/user.validator.js
app.js
middlewares/auth/auth.middleware.spec.js
middlewares/token.middleware.js

tokenmiddleware 생성
middleware 로깅 수정
2022.05.23 복세편살

feat(detail): 비로그인 상태에서도 가능하게 변경

---

API/search/index.spec.js

fix(testcode): beforeAll 시간 지연

---

API/policies/controllers/main.controller.js
API/policies/index.js
API/users/controllers/user.controller.js
API/users/services/user.service.js
middlewares/redis.middleware.js

feat(redis):main 레디스 적용

---

API/policies/controllers/main.controller.js
middlewares/redis.middleware.js

fix(main): res 양식 변경

---

API/policies/controllers/main.controller.js
API/policies/services/main.service.js
API/users/controllers/user.controller.js
API/users/controllers/user.controller.spec.js
API/users/index.js
API/users/services/user.service.js
middlewares/redis.middleware.js
middlewares/token.middleware.js

feat(user): user cashe 적용

---

API/guestbook/controllers/guestbook.controller.js
API/guestbook/index.js
API/guestbook/services/guestbook.service.js
API/mark/controllers/mark.controller.js
API/mark/services/mark.service.js
routes/index.js
schemas/guestbook.js
schemas/user.js

feat(guestbook):방명록 기능 추가

---

API/users/controllers/user.controller.js

fix(news):지역정보 반영

---

API/guestbook/controllers/guestbook.controller.js

fix(guestbook):feedId 추가

---

.gitignore
API/mail/index.spec.js
API/users/controllers/user.controller.js
API/users/controllers/user.controller.spec.js
API/users/index.js
API/users/services/user.service.js
appspec.yml
scripts/after.install.sh
scripts/application.start.sh
scripts/application.stop.sh

feat(user): redis 적용

---

API/users/controllers/user.controller.spec.js
schemas/redis.js

feat(redis): elasticashe 적용

---

schemas/redis.js

feat(redis): endpoint 재설정

---

.github/workflows/node.js.yml
API/users/controllers/user.controller.js

feat(redis): workflow에서 redisurl 삭제

---

.prettierignore
API/mail/index.spec.js
API/mail/services/mail.service.js
middlewares/auth/auth.middleware.js

feat(mail): test 메일 변경

---

app.js

fix(dev):helmet 제거

---

app.js
package-lock.json
package.json

fix(helmet):다시 추가 휴,..

---

API/tip/controllers/tip.controller.js
API/tip/controllers/tip.spec.js
openAPI/youthAPI/controllers/youth.controller.js

fix(tip):버그제보 레디스 반영

---

API/news/services/news.service.js

feat(news):기본이미지 적용

---

API/news/services/news.service.js

fix(news):기본이미지 변경

---

API/news/services/news.service.js

(fix) to main from dev

---

API/news/services/news.service.js
openAPI/youthAPI/controllers/youth.controller.js
openAPI/youthAPI/youth.local.js

feat(news):기본이미지 주소 수정

---

API/guestbook/services/guestbook.service.js
API/mark/controllers/mark.controller.js
API/mark/services/mark.service.js
API/news/services/news.service.js
openAPI/youthAPI/controllers/youth.controller.js
openAPI/youthAPI/youth.local.js
package-lock.json
package.json
schemas/index.js

feat(artillery):라이브러리 추가

---

.github/workflows/node.js.yml
.gitignore
.prettierignore
app.js
loadtest.yml
package-lock.json
package.json

feat(stresstest): stresstest 추가

---

API/users/controllers/user.controller.js

feat(user): 쓸때없는 await 삭제

---

API/mark/controllers/mark.controller.js
API/mark/services/mark.service.js
schemas/index.js

feat(mark):이메일 미완성본

---

README.md

fix(README): modify README file

---

appspec.yml

feat(CI): codebuild 과정 추가

---

API/mark/services/mark.service.js
API/news/index.js
API/users/index.js
app.js
loadtest.yml
middlewares/redis.middleware.js

북마크 한 정책의 신청기간이 7일 남았을 때 메일을 보냄
commit by pooreum

feat(mark): 이메일 완성본

---

appspec.yml

feat(CI): codebuild 과정 삭제

---

API/policies/index.spec.js
API/users/controllers/user.controller.js
API/users/controllers/user.controller.spec.js

미취업을 미취업자로 바꿔 저장하는 code 삭제
2022.05.29 복세편살

feat(user): 미취업을 미취업자로 바꿔 저장하는 code 삭제

---

loadtest.yml

feat(stresstest): 가중치 추가

---

schemas/index.js

feat(DB): atlas 적용

---

.gitignore
API/users/controllers/user.controller.js
openAPI/youthAPI/index.js
openAPI/youthAPI/youth.local.js

feat(user): 세션아이디 안보내기

---

app.js

feat(app): cors 수정

---

schemas/index.js

feat(mongo): url 수정

---

.gitignore
loadtest.yml

feat(stresstest): testusertoken 적용

---

API/policies/controllers/main.controller.js

getMain logic에서 age 기준이 없는 data 추천하지 않도록 수정

fix(getMain): modify getMain

---

API/policies/services/detail.service.js

fix(detail): modify detail service

---

API/mail/controllers/mail.controller.js
API/mark/controllers/mark.controller.js
API/news/controllers/news.controller.js
API/policies/controllers/main.controller.js
API/search/controllers/search.controller.js
API/tip/controllers/tip.controller.js
API/users/controllers/user.controller.js
middlewares/redis.middleware.js

feat(redis): console 삭제

---

.gitignore
API/guestbook/services/guestbook.service.js
app.js
openAPI/dataCleansing/cleansing.js
openAPI/dataCleansing/data.js
openAPI/youthAPI/index.js

- ignore badWord 추가
- 청년api 업종 추가
- atlas 적용

feat(guestbook):욕설 필터

---

API/policies/controllers/main.controller.js
openAPI/governmentAPI/index.js

job 조건에서 미취업자 includes 미취업으로 수정

fix(getMain): modify logic

---

API/users/controllers/user.controller.js
openAPI/centralAPI/controllers/central.age.js
openAPI/centralAPI/controllers/central.salary.js

feat(user): await 추가

---

API/users/controllers/user.controller.js

feat(user): Promise.all로 변경

---

API/mark/index.js
API/mark/services/mark.service.js
API/tip/services/tip.service.js
app.js

- 이메일 set timeout 설정 , schedule 설정
- 정책 숨기기 북마크 버그 수정
commit by youngwo

feat(mail): schdule 추가

---

openAPI/dataCleansing/cleansing.js
openAPI/dataCleansing/data.js

feat(openAPI): Primise.all 속도 테스트

---

serverTest/mailertest.yml

feat(test):target 제거

---

API/mark/controllers/mark.spec.js
API/tip/controllers/tip.spec.js

feat(test): testcode 수정

---

app.js

feat(app): app.js 오타수정

---

API/tip/controllers/tip.controller.js
API/tip/index.spec.js
test/data/sample.json

fix(testcode):tip 통합테스트 수정

---

.github/workflows/node.js.yml
API/mail/index.spec.js
API/mail/services/mail.service.js

feat(mail): test시 메일계정 테스트 mail로 변경

---

API/mark/index.spec.js
API/policies/index.spec.js
API/tip/index.spec.js

feat(test): timeout 설정

---

scripts/after.install.sh

pm2 --watch 에서 reload로 변경
2022.06.04 복세편살

feat(pm2): pm2 --watch 에서 reload로 변경

---

openAPI/centralAPI/index.js
server.js

feat(https):.https 주석

---

scripts/after.install.sh

feat(pm2):reload 주석

---

API/users/services/user.service.js
app.js
logging.js
openAPI/centralAPI/index.js
openAPI/youthAPI/index.js
stressTest/loadtest.yml

스트레스 테스트 경로 수정
ttl설정 set 하면서 바로 하도록 수정
서버 재실행때 마다 log파일 삭제하는 거 수정

feat(stresstest): 스트레스 테스트 경로 수정

---

app.js
logging.js
openAPI/centralAPI/index.js
openAPI/youthAPI/index.js

await promise.all => promise.then 로 변경
2022.06.04 복세편살

feat(openAPI): await promise.all => promise.then

---

schemas/chat.js
server.js
socket.js

fix(socket): chatroom uerId 제거

---

API/mail/index.spec.js
API/mark/index.spec.js
API/news/index.spec.js
API/policies/index.spec.js
API/search/index.spec.js
API/tip/index.spec.js
API/users/index.spec.js

feat(test): testdb url 변경

---

app.js

feat(log): log 모양 변경

---

API/mark/services/mark.service.js
API/news/services/news.service.js
API/policies/services/detail.service.js
API/tip/services/tip.service.js
API/users/services/user.service.js

feat(service): trycatch error handling

---

ecosystem.config.js
ecosystem.json
server.js

feat(pm2): pm2 clustermode 추가

---

scripts/after.install.sh

feat(pm2): sudo pm2 reload server 추가

---

server.js

feat(pm2): app -> server

---

.github/workflows/node.js.yml

feat(CI): npm i -> npm ci

---

README.md

feat(README) 비동기 처리 방식에 관한 문제 효과 링크 추가

---

API/mark/services/mark.service.js
API/news/services/news.service.js
API/policies/services/main.service.js
API/users/services/user.service.js

feat(redis): TTL 720초로 수정

---

API/users/controllers/user.controller.js
API/users/controllers/user.controller.spec.js
API/users/services/user.service.js

feat(AWS-X-Ray) 하위세그먼트 추가
